version: '3.8'

services:
  db:
    image: postgres:15
    container_name: pulse_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: pulse
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: pulse_api
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/pulse
      - WATCHFILES_FORCE_POLLING=true
    volumes:
      - .:/app

volumes:
  postgres_data:
