"""Add attachment fields

Revision ID: b9e8cfe4007c
Revises: a80adafc6e80
Create Date: 2026-07-18 04:31:44.156428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9e8cfe4007c'
down_revision: Union[str, Sequence[str], None] = 'a80adafc6e80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('attachment_name', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('attachment_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'attachment_size')
    op.drop_column('messages', 'attachment_name')
    # ### end Alembic commands ###
